### PR TITLE
Adding braindecode sprint

### PR DESCRIPTION
**Pull request by bruAristimunha**
Hello!

I am reaching out to you on behalf of the braindecode library to express our interest in organizing a brain decode code sprint during EuroScipy.

Braindecode is a scientific Python library focusing on decoding brain signals with deep learning. Our library has been built using mne-python, PyTorch, and Skorch.

Currently, we have identified some key objectives for the code sprint. These include the
1) restructuring of our documentation to make it more accessible for new users, as well as the
2) re-implementation and optimization of our data loaders.
3) re-establish a solid training structure for our library.

### CODE REVIEW

**Comment by bruAristimunha** [comment]
CC. @robintibor, @agramfort, @dengemann, @hubertjb and @sylvchev.

Can you review @datapythonista?

**Review by datapythonista — APPROVED** [review]
Lgtm, I'll leave it open for a bit in case there is feedback

**Review by glemaitre — APPROVED** [review]
I build the website locally and fixed the rendering of the sub-item.

Merging.

**Comment by glemaitre** [comment]
Thanks @bruAristimunha

**Pull request merged**
